# Generated by Django 2.2.2 on 2019-06-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmovietime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Movie',
            name='poster',
            field=models.CharField(default='https://images.8tracks.com/cover/i/009/128/165/Screen_Shot_2015-05-29_at_9.04.57_PM-151.png?rect=0,2,690,690&q=98&fm=jpg&fit=max', max_length=500),
            preserve_default=False,
        ),
    ]
