# Generated by Django 2.2.3 on 2019-07-06 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmovietime', '0003_movie_user_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_shelf',
            field=models.ManyToManyField(blank=True, related_name='movie_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
