# Generated by Django 2.2.3 on 2019-07-06 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badmovietime', '0002_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_shelf',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
